spring.application.name=verfut.front

server.port=8081

# Eureka configuration
eureka.instance.prefer-ip-address=true
#eureka.client.service-url.defaultZone=http://localhost:8762/eureka
eureka.client.service-url.defaultZone=http://3.84.37.16:8762/eureka
